version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    container_name: mqtt-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest