version: '3.8'
services:
  rabbitmq:
    build: .
    container_name: mqtt-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883 #tcp mqtt
      - 15675:15675 #websocket mqtt
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest